rpm: &rpm
  tar: tar gzip
  specs: which findutils
  zlib: zlib-devel
  openssl: openssl-devel
  yaml: libyaml-devel
  cext: gcc make
  set-locale:
    - ENV LANG=en_US.UTF-8

deb: &deb
  locale: locales
  tar:
  specs: netbase
  zlib: libz-dev
  openssl: libssl-dev
  yaml: libyaml-dev
  cext: gcc make
  set-locale:
    # Uncomment the en_US.UTF-8 line in /etc/locale.gen
    - RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen
    # locale-gen generates locales for all uncommented locales in /etc/locale.gen
    - RUN locale-gen
    - ENV LANG=en_US.UTF-8

ol7:
  base: oraclelinux:7-slim
  # --enablerepo needed for libyaml-devel
  install: RUN yum install --enablerepo=ol7_optional_latest -y
  locale:
  <<: *rpm

ol8:
  base: oraclelinux:8-slim
  # --enablerepo needed for libyaml-devel
  install: RUN microdnf install --enablerepo=ol8_codeready_builder -y
  locale: glibc-langpack-en
  <<: *rpm

fedora35:
  base: fedora:35
  install: RUN dnf install -y
  locale: glibc-langpack-en
  <<: *rpm

fedora36:
  base: fedora:36
  install: RUN dnf install -y
  locale: glibc-langpack-en
  <<: *rpm

ubuntu1604:
  base: ubuntu:16.04
  install: RUN apt-get update && apt-get install -y
  <<: *deb

ubuntu1804:
  base: ubuntu:18.04
  install: RUN apt-get update && apt-get install -y
  <<: *deb

ubuntu2004:
  base: ubuntu:20.04
  install: RUN apt-get update && apt-get install -y
  <<: *deb

ubuntu2204:
  base: ubuntu:22.04
  install: RUN apt-get update && apt-get install -y
  <<: *deb

debian10:
  base: debian:buster
  install: RUN apt-get update && apt-get install -y
  <<: *deb
